/*
Entitlements Service

The Entitlements service provides REST APIs that manage the assignments of entitlements and quotas to subaccounts and directories.   Entitlements and their quota are automatically assigned to the global account when a customer order is fulfilled. Use the APIs in this service to manage the distribution of this global quota to your directories and subaccounts.   NOTE: These APIs are relevant only for cloud management tools feature set B. For details and information about whether this applies to your global account, see [Cloud Management Tools - Feature Set Overview](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/caf4e4e23aef4666ad8f125af393dfb2.html).  See also: * [Authorization](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/3670474a58c24ac2b082e76cbbd9dc19.html) * [Rate Limiting](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77b217b3f57a45b987eb7fbc3305ce1e.html) * [Error Response Format](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77fef2fb104b4b1795e2e6cee790e8b8.html) * [Asynchronous Jobs](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/0a0a6ab0ad114d72a6611c1c6b21683e.html)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BusinessCategoryResponseObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BusinessCategoryResponseObject{}

// BusinessCategoryResponseObject struct for BusinessCategoryResponseObject
type BusinessCategoryResponseObject struct {
	// Display name of the business category for customer-facing UIs.
	DisplayName *string `json:"displayName,omitempty"`
	// Unique ID of the business category.
	Id *string `json:"id,omitempty"`
}

// NewBusinessCategoryResponseObject instantiates a new BusinessCategoryResponseObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBusinessCategoryResponseObject() *BusinessCategoryResponseObject {
	this := BusinessCategoryResponseObject{}
	return &this
}

// NewBusinessCategoryResponseObjectWithDefaults instantiates a new BusinessCategoryResponseObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBusinessCategoryResponseObjectWithDefaults() *BusinessCategoryResponseObject {
	this := BusinessCategoryResponseObject{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *BusinessCategoryResponseObject) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BusinessCategoryResponseObject) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *BusinessCategoryResponseObject) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *BusinessCategoryResponseObject) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BusinessCategoryResponseObject) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BusinessCategoryResponseObject) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BusinessCategoryResponseObject) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *BusinessCategoryResponseObject) SetId(v string) {
	o.Id = &v
}

func (o BusinessCategoryResponseObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BusinessCategoryResponseObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableBusinessCategoryResponseObject struct {
	value *BusinessCategoryResponseObject
	isSet bool
}

func (v NullableBusinessCategoryResponseObject) Get() *BusinessCategoryResponseObject {
	return v.value
}

func (v *NullableBusinessCategoryResponseObject) Set(val *BusinessCategoryResponseObject) {
	v.value = val
	v.isSet = true
}

func (v NullableBusinessCategoryResponseObject) IsSet() bool {
	return v.isSet
}

func (v *NullableBusinessCategoryResponseObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBusinessCategoryResponseObject(val *BusinessCategoryResponseObject) *NullableBusinessCategoryResponseObject {
	return &NullableBusinessCategoryResponseObject{value: val, isSet: true}
}

func (v NullableBusinessCategoryResponseObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBusinessCategoryResponseObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


