/*
Entitlements Service

The Entitlements service provides REST APIs that manage the assignments of entitlements and quotas to subaccounts and directories.   Entitlements and their quota are automatically assigned to the global account when a customer order is fulfilled. Use the APIs in this service to manage the distribution of this global quota to your directories and subaccounts.   NOTE: These APIs are relevant only for cloud management tools feature set B. For details and information about whether this applies to your global account, see [Cloud Management Tools - Feature Set Overview](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/caf4e4e23aef4666ad8f125af393dfb2.html).  See also: * [Authorization](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/3670474a58c24ac2b082e76cbbd9dc19.html) * [Rate Limiting](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77b217b3f57a45b987eb7fbc3305ce1e.html) * [Error Response Format](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77fef2fb104b4b1795e2e6cee790e8b8.html) * [Asynchronous Jobs](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/0a0a6ab0ad114d72a6611c1c6b21683e.html)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DirectoryAssignmentsRequestPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DirectoryAssignmentsRequestPayload{}

// DirectoryAssignmentsRequestPayload struct for DirectoryAssignmentsRequestPayload
type DirectoryAssignmentsRequestPayload struct {
	// The quantity of the plan to assign to the specified directory. Relevant and mandatory only for plans that have a numeric quota.  Do not set if enable=TRUE is specified.
	Amount *float32 `json:"amount,omitempty"`
	// Whether to automatically allocate the plans of entitlements that have a numeric quota with the amount specified in auto-distribute-amount to any new subaccount that is added to the directory in the future. For entitlements without a numeric quota, the plan is assigned to any new subaccount that is added to the directory in the future with the condition that enable=TRUE is set (autoDistributeAmount is not relevant in this case). If distribute=TRUE, the same assignment is also made to all subaccounts currently in the directory. Entitlements are subject to available quota in the directory.
	AutoAssign *bool `json:"autoAssign,omitempty"`
	// The quota of the specified plan to automatically allocate to any new subaccount that is created in the future in the directory. When applying this option, you must set autoAssign=TRUE and/or distribute=TRUE. Applies only to entitlements that have a numeric quota. Entitlements are subject to available quota in the directory.
	AutoDistributeAmount *int32 `json:"autoDistributeAmount,omitempty"`
	// Whether to assign the plan with the quota specified in autoDistributeAmount to subaccounts currently located in the specified directory. For entitlements without a numeric quota, such as multitenant apps, the plan is assigned to the subaccounts currently located in the directory (autoDistributeAmount is not relevant in this case). In both cases, autoAssign must be set to TRUE.
	Distribute *bool `json:"distribute,omitempty"`
	// Whether to allocate the plan to the to the specified directory without quantity restrictions. Relevant and mandatory only for plans that don't have a numeric quota. Do not use if amount is specified.
	Enable *bool `json:"enable,omitempty"`
	// The technical name of the entitlement to assign to the directory.
	Plan string `json:"plan"`
	// A unique identifier for service plans that can distinguish between the same service plans with different pricing plans.
	PlanUniqueIdentifier *string `json:"planUniqueIdentifier,omitempty"`
	// The technical name of the entitlement (service, application, environment) to assign.
	Service string `json:"service"`
}

type _DirectoryAssignmentsRequestPayload DirectoryAssignmentsRequestPayload

// NewDirectoryAssignmentsRequestPayload instantiates a new DirectoryAssignmentsRequestPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectoryAssignmentsRequestPayload(plan string, service string) *DirectoryAssignmentsRequestPayload {
	this := DirectoryAssignmentsRequestPayload{}
	this.Plan = plan
	this.Service = service
	return &this
}

// NewDirectoryAssignmentsRequestPayloadWithDefaults instantiates a new DirectoryAssignmentsRequestPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectoryAssignmentsRequestPayloadWithDefaults() *DirectoryAssignmentsRequestPayload {
	this := DirectoryAssignmentsRequestPayload{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *DirectoryAssignmentsRequestPayload) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryAssignmentsRequestPayload) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *DirectoryAssignmentsRequestPayload) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *DirectoryAssignmentsRequestPayload) SetAmount(v float32) {
	o.Amount = &v
}

// GetAutoAssign returns the AutoAssign field value if set, zero value otherwise.
func (o *DirectoryAssignmentsRequestPayload) GetAutoAssign() bool {
	if o == nil || IsNil(o.AutoAssign) {
		var ret bool
		return ret
	}
	return *o.AutoAssign
}

// GetAutoAssignOk returns a tuple with the AutoAssign field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryAssignmentsRequestPayload) GetAutoAssignOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoAssign) {
		return nil, false
	}
	return o.AutoAssign, true
}

// HasAutoAssign returns a boolean if a field has been set.
func (o *DirectoryAssignmentsRequestPayload) HasAutoAssign() bool {
	if o != nil && !IsNil(o.AutoAssign) {
		return true
	}

	return false
}

// SetAutoAssign gets a reference to the given bool and assigns it to the AutoAssign field.
func (o *DirectoryAssignmentsRequestPayload) SetAutoAssign(v bool) {
	o.AutoAssign = &v
}

// GetAutoDistributeAmount returns the AutoDistributeAmount field value if set, zero value otherwise.
func (o *DirectoryAssignmentsRequestPayload) GetAutoDistributeAmount() int32 {
	if o == nil || IsNil(o.AutoDistributeAmount) {
		var ret int32
		return ret
	}
	return *o.AutoDistributeAmount
}

// GetAutoDistributeAmountOk returns a tuple with the AutoDistributeAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryAssignmentsRequestPayload) GetAutoDistributeAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.AutoDistributeAmount) {
		return nil, false
	}
	return o.AutoDistributeAmount, true
}

// HasAutoDistributeAmount returns a boolean if a field has been set.
func (o *DirectoryAssignmentsRequestPayload) HasAutoDistributeAmount() bool {
	if o != nil && !IsNil(o.AutoDistributeAmount) {
		return true
	}

	return false
}

// SetAutoDistributeAmount gets a reference to the given int32 and assigns it to the AutoDistributeAmount field.
func (o *DirectoryAssignmentsRequestPayload) SetAutoDistributeAmount(v int32) {
	o.AutoDistributeAmount = &v
}

// GetDistribute returns the Distribute field value if set, zero value otherwise.
func (o *DirectoryAssignmentsRequestPayload) GetDistribute() bool {
	if o == nil || IsNil(o.Distribute) {
		var ret bool
		return ret
	}
	return *o.Distribute
}

// GetDistributeOk returns a tuple with the Distribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryAssignmentsRequestPayload) GetDistributeOk() (*bool, bool) {
	if o == nil || IsNil(o.Distribute) {
		return nil, false
	}
	return o.Distribute, true
}

// HasDistribute returns a boolean if a field has been set.
func (o *DirectoryAssignmentsRequestPayload) HasDistribute() bool {
	if o != nil && !IsNil(o.Distribute) {
		return true
	}

	return false
}

// SetDistribute gets a reference to the given bool and assigns it to the Distribute field.
func (o *DirectoryAssignmentsRequestPayload) SetDistribute(v bool) {
	o.Distribute = &v
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *DirectoryAssignmentsRequestPayload) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryAssignmentsRequestPayload) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *DirectoryAssignmentsRequestPayload) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *DirectoryAssignmentsRequestPayload) SetEnable(v bool) {
	o.Enable = &v
}

// GetPlan returns the Plan field value
func (o *DirectoryAssignmentsRequestPayload) GetPlan() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Plan
}

// GetPlanOk returns a tuple with the Plan field value
// and a boolean to check if the value has been set.
func (o *DirectoryAssignmentsRequestPayload) GetPlanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plan, true
}

// SetPlan sets field value
func (o *DirectoryAssignmentsRequestPayload) SetPlan(v string) {
	o.Plan = v
}

// GetPlanUniqueIdentifier returns the PlanUniqueIdentifier field value if set, zero value otherwise.
func (o *DirectoryAssignmentsRequestPayload) GetPlanUniqueIdentifier() string {
	if o == nil || IsNil(o.PlanUniqueIdentifier) {
		var ret string
		return ret
	}
	return *o.PlanUniqueIdentifier
}

// GetPlanUniqueIdentifierOk returns a tuple with the PlanUniqueIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryAssignmentsRequestPayload) GetPlanUniqueIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.PlanUniqueIdentifier) {
		return nil, false
	}
	return o.PlanUniqueIdentifier, true
}

// HasPlanUniqueIdentifier returns a boolean if a field has been set.
func (o *DirectoryAssignmentsRequestPayload) HasPlanUniqueIdentifier() bool {
	if o != nil && !IsNil(o.PlanUniqueIdentifier) {
		return true
	}

	return false
}

// SetPlanUniqueIdentifier gets a reference to the given string and assigns it to the PlanUniqueIdentifier field.
func (o *DirectoryAssignmentsRequestPayload) SetPlanUniqueIdentifier(v string) {
	o.PlanUniqueIdentifier = &v
}

// GetService returns the Service field value
func (o *DirectoryAssignmentsRequestPayload) GetService() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Service
}

// GetServiceOk returns a tuple with the Service field value
// and a boolean to check if the value has been set.
func (o *DirectoryAssignmentsRequestPayload) GetServiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Service, true
}

// SetService sets field value
func (o *DirectoryAssignmentsRequestPayload) SetService(v string) {
	o.Service = v
}

func (o DirectoryAssignmentsRequestPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DirectoryAssignmentsRequestPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.AutoAssign) {
		toSerialize["autoAssign"] = o.AutoAssign
	}
	if !IsNil(o.AutoDistributeAmount) {
		toSerialize["autoDistributeAmount"] = o.AutoDistributeAmount
	}
	if !IsNil(o.Distribute) {
		toSerialize["distribute"] = o.Distribute
	}
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	toSerialize["plan"] = o.Plan
	if !IsNil(o.PlanUniqueIdentifier) {
		toSerialize["planUniqueIdentifier"] = o.PlanUniqueIdentifier
	}
	toSerialize["service"] = o.Service
	return toSerialize, nil
}

func (o *DirectoryAssignmentsRequestPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plan",
		"service",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDirectoryAssignmentsRequestPayload := _DirectoryAssignmentsRequestPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDirectoryAssignmentsRequestPayload)

	if err != nil {
		return err
	}

	*o = DirectoryAssignmentsRequestPayload(varDirectoryAssignmentsRequestPayload)

	return err
}

type NullableDirectoryAssignmentsRequestPayload struct {
	value *DirectoryAssignmentsRequestPayload
	isSet bool
}

func (v NullableDirectoryAssignmentsRequestPayload) Get() *DirectoryAssignmentsRequestPayload {
	return v.value
}

func (v *NullableDirectoryAssignmentsRequestPayload) Set(val *DirectoryAssignmentsRequestPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectoryAssignmentsRequestPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectoryAssignmentsRequestPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectoryAssignmentsRequestPayload(val *DirectoryAssignmentsRequestPayload) *NullableDirectoryAssignmentsRequestPayload {
	return &NullableDirectoryAssignmentsRequestPayload{value: val, isSet: true}
}

func (v NullableDirectoryAssignmentsRequestPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectoryAssignmentsRequestPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


