/*
SAP XSUAA REST API

Provides access to RoleTemplates, Roles, RoleCollection etc. using the XSUAA REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


type ScimGroupEndpointsAPI interface {

	/*
	CreateGroup Method for CreateGroup

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ScimGroupEndpointsAPICreateGroupRequest
	*/
	CreateGroup(ctx context.Context) ScimGroupEndpointsAPICreateGroupRequest

	// CreateGroupExecute executes the request
	//  @return ScimGroup
	CreateGroupExecute(r ScimGroupEndpointsAPICreateGroupRequest) (*ScimGroup, *http.Response, error)

	/*
	ListGroups Method for ListGroups

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ScimGroupEndpointsAPIListGroupsRequest
	*/
	ListGroups(ctx context.Context) ScimGroupEndpointsAPIListGroupsRequest

	// ListGroupsExecute executes the request
	//  @return SearchResultsObject
	ListGroupsExecute(r ScimGroupEndpointsAPIListGroupsRequest) (*SearchResultsObject, *http.Response, error)
}

// ScimGroupEndpointsAPIService ScimGroupEndpointsAPI service
type ScimGroupEndpointsAPIService service

type ScimGroupEndpointsAPICreateGroupRequest struct {
	ctx context.Context
	ApiService ScimGroupEndpointsAPI
	scimGroup *ScimGroup
}

func (r ScimGroupEndpointsAPICreateGroupRequest) ScimGroup(scimGroup ScimGroup) ScimGroupEndpointsAPICreateGroupRequest {
	r.scimGroup = &scimGroup
	return r
}

func (r ScimGroupEndpointsAPICreateGroupRequest) Execute() (*ScimGroup, *http.Response, error) {
	return r.ApiService.CreateGroupExecute(r)
}

/*
CreateGroup Method for CreateGroup

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ScimGroupEndpointsAPICreateGroupRequest
*/
func (a *ScimGroupEndpointsAPIService) CreateGroup(ctx context.Context) ScimGroupEndpointsAPICreateGroupRequest {
	return ScimGroupEndpointsAPICreateGroupRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ScimGroup
func (a *ScimGroupEndpointsAPIService) CreateGroupExecute(r ScimGroupEndpointsAPICreateGroupRequest) (*ScimGroup, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ScimGroup
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ScimGroupEndpointsAPIService.CreateGroup")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Groups"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.scimGroup == nil {
		return localVarReturnValue, nil, reportError("scimGroup is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.scimGroup
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ScimGroupEndpointsAPIListGroupsRequest struct {
	ctx context.Context
	ApiService ScimGroupEndpointsAPI
	attributes *string
	filter *string
	sortBy *string
	sortOrder *string
	startIndex *int32
	count *int32
}

func (r ScimGroupEndpointsAPIListGroupsRequest) Attributes(attributes string) ScimGroupEndpointsAPIListGroupsRequest {
	r.attributes = &attributes
	return r
}

func (r ScimGroupEndpointsAPIListGroupsRequest) Filter(filter string) ScimGroupEndpointsAPIListGroupsRequest {
	r.filter = &filter
	return r
}

func (r ScimGroupEndpointsAPIListGroupsRequest) SortBy(sortBy string) ScimGroupEndpointsAPIListGroupsRequest {
	r.sortBy = &sortBy
	return r
}

func (r ScimGroupEndpointsAPIListGroupsRequest) SortOrder(sortOrder string) ScimGroupEndpointsAPIListGroupsRequest {
	r.sortOrder = &sortOrder
	return r
}

func (r ScimGroupEndpointsAPIListGroupsRequest) StartIndex(startIndex int32) ScimGroupEndpointsAPIListGroupsRequest {
	r.startIndex = &startIndex
	return r
}

func (r ScimGroupEndpointsAPIListGroupsRequest) Count(count int32) ScimGroupEndpointsAPIListGroupsRequest {
	r.count = &count
	return r
}

func (r ScimGroupEndpointsAPIListGroupsRequest) Execute() (*SearchResultsObject, *http.Response, error) {
	return r.ApiService.ListGroupsExecute(r)
}

/*
ListGroups Method for ListGroups

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ScimGroupEndpointsAPIListGroupsRequest
*/
func (a *ScimGroupEndpointsAPIService) ListGroups(ctx context.Context) ScimGroupEndpointsAPIListGroupsRequest {
	return ScimGroupEndpointsAPIListGroupsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return SearchResultsObject
func (a *ScimGroupEndpointsAPIService) ListGroupsExecute(r ScimGroupEndpointsAPIListGroupsRequest) (*SearchResultsObject, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SearchResultsObject
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ScimGroupEndpointsAPIService.ListGroups")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Groups"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.attributes != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "attributes", r.attributes, "form", "")
	}
	if r.filter != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "filter", r.filter, "form", "")
	} else {
		var defaultValue string = "id pr"
		r.filter = &defaultValue
	}
	if r.sortBy != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sortBy", r.sortBy, "form", "")
	} else {
		var defaultValue string = "displayName"
		r.sortBy = &defaultValue
	}
	if r.sortOrder != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sortOrder", r.sortOrder, "form", "")
	} else {
		var defaultValue string = "ascending"
		r.sortOrder = &defaultValue
	}
	if r.startIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "startIndex", r.startIndex, "form", "")
	} else {
		var defaultValue int32 = 1
		r.startIndex = &defaultValue
	}
	if r.count != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "count", r.count, "form", "")
	} else {
		var defaultValue int32 = 100
		r.count = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
