/*
SAP XSUAA REST API

Provides access to RoleTemplates, Roles, RoleCollection etc. using the XSUAA REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CustomIdpCockpitResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomIdpCockpitResponse{}

// CustomIdpCockpitResponse struct for CustomIdpCockpitResponse
type CustomIdpCockpitResponse struct {
	MoreTrustsAllowed *bool `json:"moreTrustsAllowed,omitempty"`
}

// NewCustomIdpCockpitResponse instantiates a new CustomIdpCockpitResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomIdpCockpitResponse() *CustomIdpCockpitResponse {
	this := CustomIdpCockpitResponse{}
	return &this
}

// NewCustomIdpCockpitResponseWithDefaults instantiates a new CustomIdpCockpitResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomIdpCockpitResponseWithDefaults() *CustomIdpCockpitResponse {
	this := CustomIdpCockpitResponse{}
	return &this
}

// GetMoreTrustsAllowed returns the MoreTrustsAllowed field value if set, zero value otherwise.
func (o *CustomIdpCockpitResponse) GetMoreTrustsAllowed() bool {
	if o == nil || IsNil(o.MoreTrustsAllowed) {
		var ret bool
		return ret
	}
	return *o.MoreTrustsAllowed
}

// GetMoreTrustsAllowedOk returns a tuple with the MoreTrustsAllowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomIdpCockpitResponse) GetMoreTrustsAllowedOk() (*bool, bool) {
	if o == nil || IsNil(o.MoreTrustsAllowed) {
		return nil, false
	}
	return o.MoreTrustsAllowed, true
}

// HasMoreTrustsAllowed returns a boolean if a field has been set.
func (o *CustomIdpCockpitResponse) HasMoreTrustsAllowed() bool {
	if o != nil && !IsNil(o.MoreTrustsAllowed) {
		return true
	}

	return false
}

// SetMoreTrustsAllowed gets a reference to the given bool and assigns it to the MoreTrustsAllowed field.
func (o *CustomIdpCockpitResponse) SetMoreTrustsAllowed(v bool) {
	o.MoreTrustsAllowed = &v
}

func (o CustomIdpCockpitResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomIdpCockpitResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MoreTrustsAllowed) {
		toSerialize["moreTrustsAllowed"] = o.MoreTrustsAllowed
	}
	return toSerialize, nil
}

type NullableCustomIdpCockpitResponse struct {
	value *CustomIdpCockpitResponse
	isSet bool
}

func (v NullableCustomIdpCockpitResponse) Get() *CustomIdpCockpitResponse {
	return v.value
}

func (v *NullableCustomIdpCockpitResponse) Set(val *CustomIdpCockpitResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomIdpCockpitResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomIdpCockpitResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomIdpCockpitResponse(val *CustomIdpCockpitResponse) *NullableCustomIdpCockpitResponse {
	return &NullableCustomIdpCockpitResponse{value: val, isSet: true}
}

func (v NullableCustomIdpCockpitResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomIdpCockpitResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


