openapi: 3.0.1
info:
  contact: {}
  description: "Provides access to RoleTemplates, Roles, RoleCollection etc. using\
    \ the XSUAA REST API"
  license:
    name: "SAP SE, Walldorf, Germany"
    url: https://support.sap.com/en/my-support/keys.html
  termsOfService: ""
  title: SAP XSUAA REST API
  version: 1.0.0
servers:
- description: Generated server url
  url: https://xsuaa-provisioning.cf.sap.hana.ondemand.com
tags:
- description: API for providing access to XSUAA applications
  name: application
- description: API for providing access to XSUAA IDP groups to role collections mappings
  name: idp-role-collection
- description: API for providing access to XSUAA identity providers
  name: identity-providers
- description: API for providing access to the XSUAA roles
  name: roles
- description: API for managing user entries and role collections assignments
  name: usercontroller
- description: API for providing access to the XSUAA role templates
  name: roletemplates
- description: API to check if more custom platform IdP trusts are allowed
  name: customidp
- description: API for providing access to the xsuaa role collections
  name: rolecollections
- description: The tenants API
  name: tenant
- description: API to set the neoAuthN flag or check if set
  name: customidp
paths:
  /sap/rest/user:
    post:
      description: Creates a new user from the payload
      operationId: createUser
      summary: Create user
      tags:
      - usercontroller
    put:
      description: Updates an existing user
      operationId: updateUser
      summary: Update a user
      tags:
      - usercontroller
  /sap/rest/user/origin/{origin}/name/{userName}/rolecollections/{roleCollectionName}:
    delete:
      description: Unassigns a role collection from a user.
      operationId: removeRoleCollection
      summary: Remove role collection from user
      tags:
      - usercontroller
    put:
      description: Assigns a role collection to a user. The user can be created if
        they do not exist yet.
      operationId: addRoleCollection
      summary: Add role collection to user
      tags:
      - usercontroller
  /sap/rest/platform-identity-providers-global/{originKey}:
    delete:
      description: Deletes a custom platform IdP and distributes the information in
        the own region.
      operationId: deletePlatformIdentityProvider
      security:
      - xs_idp_global:
        - xs_idp_global.write
      summary: Deletes a custom platform identity provider.
      tags:
      - platform-identity-providers-global
    get:
      description: Reads a custom platform IdP from own region.
      operationId: getPlatformIdentityProvider
      security:
      - xs_idp_global:
        - xs_idp_global.write
      summary: Reads a custom platform identity provider.
      tags:
      - platform-identity-providers-global
    put:
      description: Updates a custom platform IdP and distributes the information in
        the own region.
      operationId: updatePlatformIdentityProvider
      security:
      - xs_idp_global:
        - xs_idp_global.write
      summary: Updates a custom platform identity provider.
      tags:
      - platform-identity-providers-global
  /sap/rest/identity-providers/{id}:
    delete:
      operationId: deleteIdentityProvider
      tags:
      - identity-providers
    get:
      description: Returns an identity provider specified by the id of the identity
        provider.
      operationId: retrieveIdentityProvider
      security:
      - xs_auth:
        - xs_idp.read
      summary: Returns an identity provider.
      tags:
      - identity-providers
    put:
      operationId: updateIdentityProvider
      tags:
      - identity-providers
  /sap/rest/identity-providers/migrate/{origin}:
    put:
      operationId: migrateSAMLToOIDCIDP
      tags:
      - identity-providers
  /sap/rest/identity-providers/migrate/{origin}/rollback:
    put:
      operationId: rollbackSAMLToOIDCIDP
      tags:
      - identity-providers
  /sap/rest/authorization/v2/rolecollections/{roleCollectionName}:
    delete:
      description: Deletes a role collection specified by the name of the role collection.
      operationId: deleteRoleCollectionByName
      security:
      - xs_auth:
        - xs_authorization.write
      summary: Deletes a role collection.
      tags:
      - rolecollections
    get:
      description: Returns information about a role collection identified by the name
        of the role collection.
      operationId: getRoleCollectionByName
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns a role collection.
      tags:
      - rolecollections
    put:
      description: Updates the description of a role collection specified by the name
        of the role collection. You cannot change any other attribute of the role
        collection.
      operationId: changeRoleCollectionDescription
      security:
      - xs_auth:
        - xs_authorization.read
        - xs_authorization.write
      summary: Updates the description of a role collection.
      tags:
      - rolecollections
  /sap/rest/authorization/v2/rolecollections/{roleCollectionName}/roles:
    delete:
      description: "Updates a role collection by removing an array of roles from role\
        \ collection. Specify the roles by role name, application ID, and role template\
        \ name. These roles are removed from the role collection."
      operationId: deleteRolesFromRoleCollection
      security:
      - xs_auth:
        - xs_authorization.read
        - xs_authorization.write
      summary: Remove roles from role collection.
      tags:
      - rolecollections
    get:
      description: Returns information about the roles of a role collection specified
        by the name of the role collection.
      operationId: getRolesByRoleCollectionName
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns the roles of a role collection.
      tags:
      - rolecollections
    put:
      description: "Updates a role collection with an array of roles. Specify the\
        \ roles by role name, application ID, and role template name. These roles\
        \ are added to the roles already included in the role collection."
      operationId: addRolesToRoleCollection
      security:
      - xs_auth:
        - xs_authorization.write
        - xs_authorization.write
      summary: Add roles to role collection.
      tags:
      - rolecollections
  /sap/rest/authorization/v2/rolecollections/{roleCollectionName}/roles/{roleTemplateAppID}/{roleName}/{roleTemplateName}:
    delete:
      description: Deletes a role specified by the role reference from a role collection.
      operationId: deleteRoleFromRoleCollection
      security:
      - xs_auth:
        - xs_authorization.read
        - xs_authorization.write
      summary: Deletes a role from a role collection.
      tags:
      - rolecollections
    put:
      description: "Adds a role reference, specified by role name, application ID,\
        \ and role template name, to a role collection."
      operationId: addRoleToRoleCollection
      security:
      - xs_auth:
        - xs_authorization.read
        - xs_authorization.write
      summary: Adds a role to role a collection.
      tags:
      - rolecollections
  /sap/rest/authorization/v2/apps/{appId}/roletemplates/{templateName}/roles/{roleName}:
    delete:
      description: "Deletes a role specfied by app ID, role template name, and role\
        \ name."
      operationId: deleteRoleByRoleName
      security:
      - xs_auth:
        - xs_authorization.read
        - xs_authorization.write
      summary: Deletes a role.
      tags:
      - roles
    get:
      description: "Returns a role specified by the app ID, role template, and role\
        \ name."
      operationId: getRoleByAppAndRoleTemplate
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns the role of a service instance.
      tags:
      - roles
    put:
      description: "Updates a role specfied by app ID, role template name, and role\
        \ name."
      operationId: updateRole
      security:
      - xs_auth:
        - xs_authorization.read
        - xs_authorization.write
      summary: Updates a role
      tags:
      - roles
  /sap/rest/user/bulk:
    post:
      description: Creates a set of users from the list in the payload
      operationId: createUsers
      summary: Create multiple users
      tags:
      - usercontroller
  /sap/rest/platform-identity-providers-global:
    get:
      description: Reads all custom platform IdPs from own region.
      operationId: getPlatformIdentityProviders
      security:
      - xs_idp_global:
        - xs_idp_global.write
      summary: Reads all custom platform identity providers.
      tags:
      - platform-identity-providers-global
    post:
      description: Creates a custom platform IdP and distributes the information in
        the own region.
      operationId: createPlatformIdentityProvider
      security:
      - xs_idp_global:
        - xs_idp_global.write
      summary: Creates a custom platform identity provider.
      tags:
      - platform-identity-providers-global
  /sap/rest/platform-identity-providers-global/{originKey}/globalaccountids:
    get:
      description: Reads GlobalAccountIds of a custom platform IdP.
      operationId: getPlatformIdentityProviderGlobalAccountIds
      security:
      - xs_idp_global:
        - xs_idp_global.read
      summary: Reads GlobalAccountIds.
      tags:
      - platform-identity-providers-global
    post:
      description: Adds a globalAccountId to a custom platform IdP.
      operationId: addPlatformIdentityProviderGlobalAccountId
      security:
      - xs_idp_global:
        - xs_idp_global.write
      summary: Adds a globalAccountId.
      tags:
      - platform-identity-providers-global
  /sap/rest/platform-identity-providers-global/refreshTrusts:
    post:
      description: Refreshes all platform Identity Provider trusts or trusts provided
        in the body.
      operationId: refreshPlatformIdentityProviderTrusts
      security:
      - xs_idp_global:
        - xs_idp_global.write
      summary: Refreshes platform Identity Provider trusts.
      tags:
      - platform-identity-providers-global
  /sap/rest/identity-providers:
    get:
      description: Returns a list of identity providers for the current subaccount.
      operationId: retrieveIdentityProviders
      security:
      - xs_auth:
        - xs_idp.read
      summary: Returns a list of identity providers.
      tags:
      - identity-providers
    post:
      description: Creates an identity provider based on a configuration in JSON format.
      operationId: createIdentityProvider
      security:
      - xs_auth:
        - xs_idp.write
      summary: Creates an identity provider.
      tags:
      - identity-providers
  /sap/rest/globalaccount/{globalAccountId}/platform-identity-providers:
    get:
      description: Reads all platform identity providers as help values for token
        GA.
      operationId: getPlatformIdentityProvidersForGA
      security:
      - xs_idp:
        - xs_idp.read
      summary: Reads all platform IdPs for token GA.
      tags:
      - platform-identity-providers
    post:
      description: Adds a Trust for a platform identity provider.
      operationId: addPlatformIdentityProviderTrust
      security:
      - xs_idp:
        - xs_idp.write
      summary: Adds GA Trust for a given origin.
      tags:
      - platform-identity-providers
  /sap/rest/authorization/v2/users/current/rolecollections:
    delete:
      description: delete role collections for a user
      operationId: deleteRoleCollectionsForUser
      security:
      - xs_auth:
        - xs_authorization.write
      summary: Delete bulk role collections of User
      tags:
      - rolecollections
    get:
      description: all role collections for a user
      operationId: getRoleCollectionsForUser_1
      summary: Get role collections of User
      tags:
      - rolecollections
    post:
      description: create role collections for a user
      operationId: createRoleCollectionsForUser
      security:
      - xs_auth:
        - xs_authorization.write
      summary: Create bulk role collections for a User
      tags:
      - rolecollections
  /sap/rest/authorization/v2/rolecollections:
    get:
      description: "Returns all role collections which exist within the current subaccount,\
        \ sorted alphabetically by their names."
      operationId: getRoleCollections
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns role collections.
      tags:
      - rolecollections
    post:
      description: "Creates a role collection. You must include a role name at a minimum.\
        \ The description is created as null if you do not include one. You can include\
        \ role references as defined by the role name, the application ID, and role\
        \ template name. To assign group members use the /Groups endpoint. Groups\
        \ are mapped to role collections in the Authorization and Trust Management\
        \ service."
      operationId: createRoleCollection
      security:
      - xs_auth:
        - xs_authorization.read
        - xs_authorization.write
      summary: Creates a role collection.
      tags:
      - rolecollections
  /sap/rest/authorization/v2/rolecollections/bulk:
    delete:
      description: Bulk delete of role collections specified by the name of the role
        collection.
      operationId: deleteRoleCollections
      security:
      - xs_auth:
        - xs_authorization.write
      summary: Bulk delete of role collections.
      tags:
      - rolecollections
    post:
      description: Bulk create of role collections specified by the name of the role
        collection.
      operationId: createRoleCollections
      security:
      - xs_auth:
        - xs_authorization.write
      summary: Bulk creation of role collections.
      tags:
      - rolecollections
  /sap/rest/authorization/v2/identity-providers/{origin}/attributes:
    post:
      description: Add an attribute with value and operation to current IdP and application
        role collection.
      operationId: addIdpAttributeToRoleCollection
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Add a Idp attribute with value and operator to a role collection
      tags:
      - idp-role-collection
  /sap/rest/authorization/v2/apps/roles:
    post:
      description: Create a role for an application based on a role template. You
        must define the role name and description as well as identify the application
        and the role template name that you want to include in the role. The role
        inherits the scopes of the role template.
      operationId: createRole
      security:
      - xs_auth:
        - xs_authorization.read
        - xs_authorization.write
      summary: Creates a role for an application.
      tags:
      - roles
  /Users:
    get:
      operationId: findUsers
      tags:
      - scim-user-endpoints
    post:
      operationId: createUser_1
      tags:
      - scim-user-endpoints
  /Groups:
    get:
      operationId: listGroups
      tags:
      - scim-group-endpoints
    post:
      operationId: createGroup
      tags:
      - scim-group-endpoints
  /sap/rest/globalaccount/{globalAccountId}/platform-identity-providers/{originKey}:
    delete:
      description: Deletes a trust for a platform identity provider.
      operationId: deletePlatformIdentityProviderTrust
      security:
      - xs_idp:
        - xs_idp.write
      summary: Deletes a GA Trust for given origin.
      tags:
      - platform-identity-providers
    patch:
      description: Updates a trust for a platform identity provider.
      operationId: updatePlatformIdentityProviderTrust
      security:
      - xs_idp:
        - xs_idp.write
      summary: Updates a GA Trust for given origin.
      tags:
      - platform-identity-providers
  /sap/rest/authorization/v2/securitySettings:
    get:
      operationId: readSettings
      security:
      - tenant_auth:
        - xs_tenant.read
        - xs_authorization.read
      summary: Reads settings of a tenant
      tags:
      - tenant
    patch:
      description: Updates settings of a tenant
      operationId: updateSettings
      security:
      - tenant_auth:
        - xs_authorization.write
        - xs_tenant.write
      tags:
      - tenant
  /sap/rest/user/origin:
    get:
      description: Returns all unique origin values of all users in the account.
      operationId: getOrigins
      summary: Get origins of users
      tags:
      - usercontroller
  /sap/rest/user/origin/{origin}/name:
    get:
      description: "Returns all usernames in the account, sorted alphabetically"
      operationId: getUserNames
      summary: Get usernames
      tags:
      - usercontroller
  /sap/rest/user/origin/{origin}/name/{username}:
    get:
      description: Returns the user record of the specified username and origin
      operationId: getUserByName
      summary: Get a specifiy user
      tags:
      - usercontroller
  /sap/rest/user/id/{id}:
    delete:
      description: Deletes an existing user with the specified user ID
      operationId: deleteUserById
      summary: Delete a user
      tags:
      - usercontroller
    get:
      description: Retrieves a user with the specified ID
      operationId: getUserById
      summary: Read user by ID
      tags:
      - usercontroller
  /sap/rest/tenantLoginInfo/{subdomain}:
    get:
      operationId: getZoneInformationBySubdomain
      summary: Get Zone information for tenant
      tags:
      - zone-trust-information
  /sap/rest/neo/platformidentityproviders:
    get:
      description: Returns the feature flag value for a neo user for a IAS tenant
      operationId: getCustomIdPFeatureFlagForNeoUser
      summary: Returns the feature flag value for a neo user for a IAS tenant
      tags:
      - customidp
  /sap/rest/identity-providers/ias:
    get:
      description: "For the current XSUAA tenant, returns those IAS tenants for which\
        \ no SAML trust has been set up yet."
      operationId: retrieveIasTenants
      security:
      - xs_auth:
        - xs_idp.read
      summary: Returns a list of valid IAS tenants.
      tags:
      - identity-providers
  /sap/rest/identity-providers/ias/{tenantURL}:
    get:
      description: Returns a specific IAS tenants for the current XSUAA tenant.
      operationId: retrieveSpecificIasTenant
      security:
      - xs_auth:
        - xs_idp.read
      summary: Returns a specific IAS tenant.
      tags:
      - identity-providers
  /sap/rest/identity-providers/ias/status:
    get:
      description: Returns the current status of the IAS registry component. This
        includes a json payload containing errors or a health statement.
      operationId: getRegistryStatus
      summary: Returns the status of IAS registry.
      tags:
      - identity-providers
  /sap/rest/identity-providers/btpcli/identity-providers:
    get:
      deprecated: true
      operationId: retrieveIdentityProvidersForBtpCliDeprecated
      tags:
      - identity-providers
  /sap/rest/globalaccount/{globalAccountId}/platform-identity-providers/status:
    get:
      description: Return whether multiple custom platform IdP trusts are allowed
      operationId: areMoreTrustsAllowed
      security:
      - xs_idp:
        - xs_idp.read
      summary: Return whether multiple custom platform IdP trusts are allowed
      tags:
      - customidp
  /sap/rest/authorization/v2/zoneinfo/{subdomain}:
    get:
      operationId: getZoneInformationBySubdomain_1
      summary: Get Zone information for tenant
      tags:
      - zone-trust-information
  /sap/rest/authorization/v2/users/{userId}/rolecollections:
    get:
      description: all role collections for a user
      operationId: getRoleCollectionsForUser
      summary: Get role collections of User
      tags:
      - rolecollections
  /sap/rest/authorization/v2/securitySettings/public:
    get:
      operationId: readPublicSettings
      summary: Reads public settings of a tenant
      tags:
      - tenant
  /sap/rest/authorization/v2/roles:
    get:
      description: "Returns all application roles for all service instances which\
        \ are registered at UAA as OAuth2 client, sorted alphabetically by their name\
        \ and roleTemplateAppId. The roles that are returned are limited to the subaccount\
        \ credentials that are used for this request."
      operationId: getRoles
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns the roles of all service instances.
      tags:
      - roles
  /sap/rest/authorization/v2/rolecollections/roles/{appId}/{roleTemplateName}/{roleName}:
    get:
      description: "Retrieve all RoleCollections containing a role. The role is identified\
        \ by appId, roleTemplateName and role name."
      operationId: getRoleCollectionsByAppIdTemplateNameAndRoleName
      security:
      - xs_auth:
        - xs_authorization.read
        - xs_authorization.write
      summary: "Get RoleCollections containing a role identified by appId, roleTemplateName\
        \ and role name"
      tags:
      - rolecollections
      - application
  /sap/rest/authorization/v2/rolecollections/pages/{pageId}:
    get:
      description: Returns the specified page of role collection search result. The
        role collections are the result of a previous paged GET request for role collections
        of the current subaccount.
      operationId: getRoleCollectionsByPaging
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns a page of role collections.
      tags:
      - rolecollections
  /sap/rest/authorization/v2/rolecollections/pages:
    get:
      description: Returns the specified page of role collection search result. The
        role collections are the result of a previous paged GET request for role collections
        of the current subaccount.
      operationId: getRoleCollectionsByPaging_1
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns a page of role collections.
      tags:
      - rolecollections
  /sap/rest/authorization/v2/rolecollections/pages/:
    get:
      description: Returns the specified page of role collection search result. The
        role collections are the result of a previous paged GET request for role collections
        of the current subaccount.
      operationId: getRoleCollectionsByPaging_2
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns a page of role collections.
      tags:
      - rolecollections
  /sap/rest/authorization/v2/ownapp:
    get:
      description: Returns information about the service instance which is associated
        with the client credentials you submitted with this REST call.
      operationId: getOwnApp
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns information about the service instance used to execute this
        API access.
      tags:
      - application
  /sap/rest/authorization/v2/ownapp/usage:
    get:
      description: Returns the number of subscribers for the service instance which
        is associated with the client credentials you submitted with this REST call.
      operationId: getAppByToken
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns usage information for the service instance which is used to
        execute API access.
      tags:
      - application
  /sap/rest/authorization/v2/identity-providers/{origin}/rolecollections/{roleCollectionName}:
    get:
      description: Read all attributes for current IdP and application role collection.
      operationId: getIdpAttributeValuesFromRoleCollection
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Get attributes and role collections from IdP
      tags:
      - idp-role-collection
  /sap/rest/authorization/v2/identity-providers/{origin}/attributes/{attributeName}/{attributeValue}:
    get:
      description: List of application role collections which are assigned to the
        current idP and the current attribute/value
      operationId: getRoleCollectionByAttributeValue
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Read role collections from current attribute value and IdP
      tags:
      - idp-role-collection
  /sap/rest/authorization/v2/identity-providers/{origin}/attributes/{attributeName}/rolecollections/{roleCollectionName}:
    get:
      description: ist of Idp attribute value of a role collection for current attribute
        name
      operationId: getIdpAttributeValuesFromRoleCollectionByAttribute
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Read all attributes for current IdP and application role collection
      tags:
      - idp-role-collection
  /sap/rest/authorization/v2/identity-providers/{origin}/attributes/rolecollections:
    get:
      description: Read all attributes for current IdP and application role collection.
      operationId: getIdpAttributeValues
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Get attributes and role collection of IdP
      tags:
      - idp-role-collection
  /sap/rest/authorization/v2/apps:
    get:
      description: Returns all service instances of the current subaccount which are
        registered at the Authorization and Trust Management service as OAuth 2.0
        clients. The system provides information about the XSUAA application and its
        OAuth client.
      operationId: getApps
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns registered service instances of the current subaccount.
      tags:
      - application
  /sap/rest/authorization/v2/apps/{id}:
    get:
      description: Returns information about an XSUAA application instance specified
        by the app ID or service instance ID. The XSUAA application instance paired
        with an OAuth client defines a service instance of the Authorization and Trust
        Management service.
      operationId: getAppById
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns information about an XSUAA application instance.
      tags:
      - application
  /sap/rest/authorization/v2/apps/{appId}/scopes:
    get:
      description: Returns all scopes of an application protected by a service instance
        of the Authorization and Trust Management service.
      operationId: listScopes
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns the scopes of an application.
      tags:
      - application
  /sap/rest/authorization/v2/apps/{appId}/scopes/{scopeName}:
    get:
      description: Returns information about a specific scope of a specific application.
      operationId: getScope
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns the scope of an application.
      tags:
      - application
  /sap/rest/authorization/v2/apps/{appId}/roletemplates:
    get:
      description: Returns information about all role templates for an application
        that is specified by the application ID.
      operationId: getRoleTemplateByAppName
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns role templates for an application.
      tags:
      - roletemplates
  /sap/rest/authorization/v2/apps/{appId}/roletemplates/{templateName}:
    get:
      description: "Returns information about a role template of an application, which\
        \ is specified by the application ID and the role template name."
      operationId: getRoleTemplateByName
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns a role template of an application.
      tags:
      - roletemplates
  /sap/rest/authorization/v2/apps/{appId}/roles:
    get:
      description: Returns all roles of an application specified by the application
        ID.
      operationId: getRolesByAppId
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns the roles of an application
      tags:
      - roles
  /sap/rest/authorization/v2/apps/{appId}/authorizationData:
    get:
      description: Retrieve authorization data for a given appId.
      operationId: getAuthorizationData
      security:
      - xs_auth:
        - xs_authorization.read
      summary: 'Get authorization data '
      tags:
      - ams
  /sap/rest/authorization/v2/apps/{appId}/authorities:
    get:
      description: Returns a list of authorities that have been granted to an application.
        <ul><li>The granting application is identified by the <var>grantedByAppGuid</var>
        or <var>grantedByAppId</var> parameter. If no granting application is specified
        the list will be empty.</li><li>The request has to be authenticated with a
        JWT obtained via the client credentials grant from the granted application.
        The JWT has to include the <var>uaa.resource</var> scope.</li></ul>
      operationId: getGrantedAuthorities
      security:
      - uaa.resource:
        - uaa.resource
      summary: Returns a list of authorities granted to an application.
      tags:
      - application
  /sap/rest/authorization/v2/apps/roletemplates:
    get:
      description: "Returns information about all role templates of applications protected\
        \ by the service instance of the Authorization and Trust Management service.\
        \ description: Returns all role templates"
      operationId: getRoleTemplates
      security:
      - xs_auth:
        - xs_authorization.read
      summary: Returns all role templates.
      tags:
      - roletemplates
  /sap/rest/user/origin/{origin}/name/{userName}:
    delete:
      description: Deletes an existing user with the specified username and origin
      operationId: deleteUserByName
      summary: Delete a user by username and origin
      tags:
      - usercontroller
  /sap/rest/platform-identity-providers-global/{originKey}/globalaccountids/{globalAccountId}:
    delete:
      description: Deletes a globalAccountId to a custom platform IdP.
      operationId: deletePlatformIdentityProviderGlobalAccountId
      security:
      - xs_idp_global:
        - xs_idp_global.write
      summary: Deletes a globalAccountId.
      tags:
      - platform-identity-providers-global
  /sap/rest/identity-providers/originKey/{originKey}:
    delete:
      operationId: deleteIdentityProviderUsingOriginKey
      tags:
      - identity-providers
  ? /sap/rest/authorization/v2/identity-providers/{origin}/attributes/{attributeName}/{operator}/{attributeValue}/rolecollections/{roleCollectionName}
  : delete:
      description: Delete an attribute value for the current attribute within current
        IdP and application role collection
      operationId: deleteIdpAttributeToRoleCollection
      security:
      - xs_auth:
        - xs_authorization.read
      summary: delete attribute with value from a role collection
      tags:
      - idp-role-collection
  /sap/rest/identity-providers/btpcli/originKey/{originKey}:
    delete:
      deprecated: true
      operationId: retrieveIdentityProviderByOriginKeyDeprecated_3
      tags:
      - identity-providers
    get:
      deprecated: true
      operationId: retrieveIdentityProviderByOriginKeyDeprecated_5
      tags:
      - identity-providers
    head:
      deprecated: true
      operationId: retrieveIdentityProviderByOriginKeyDeprecated
      tags:
      - identity-providers
    options:
      deprecated: true
      operationId: retrieveIdentityProviderByOriginKeyDeprecated_2
      tags:
      - identity-providers
    patch:
      deprecated: true
      operationId: retrieveIdentityProviderByOriginKeyDeprecated_6
      tags:
      - identity-providers
    post:
      deprecated: true
      operationId: retrieveIdentityProviderByOriginKeyDeprecated_4
      tags:
      - identity-providers
    put:
      deprecated: true
      operationId: retrieveIdentityProviderByOriginKeyDeprecated_1
      tags:
      - identity-providers
components:
  securitySchemes:
    xs_auth:
      description: This API uses OAuth2 with the client-credentials flow.
      flows:
        clientCredentials:
          authorizationUrl: /token
          scopes:
            xs_authorization.read: for read operations
            xs_authorization.write: for create and update operations
      name: xs_auth
      type: oauth2
    xs_sub:
      description: This API uses OAuth2 with the client-credentials flow.
      flows:
        clientCredentials:
          authorizationUrl: /token
          scopes:
            xs_subscription.read: for read operations
            xs_subscription.write: for create and update operations
      name: xs_sub
      type: oauth2
    xs_tenant:
      description: This API uses OAuth2 with the client-credentials flow.
      flows:
        clientCredentials:
          authorizationUrl: /token
          scopes:
            xs_tenant.read: for read operations
            xs_tenant.write: for create and update operations
      name: xs_tenant
      type: oauth2
    xs_idp:
      description: This API uses OAuth2 with the client-credentials flow.
      flows:
        clientCredentials:
          authorizationUrl: /token
          scopes:
            xs_idp.read: for read operations
            xs_idp.write: for modifying operations
      name: xs_idp
      type: oauth2
    xs_idp_global:
      description: This API uses OAuth2 with the client-credentials flow.
      flows:
        clientCredentials:
          authorizationUrl: /token
          scopes:
            xs_idp_global.read: for read operations
            xs_idp_global.write: for modifying operations
      name: xs_idp_global
      type: oauth2
    uaa.resource:
      description: This API uses OAuth2 with the client-credentials flow.
      flows:
        clientCredentials:
          authorizationUrl: /token
          scopes:
            uaa.resource: Identifies a JWT obtained via the client credentials grant.
      name: uaa.resource
      type: oauth2
