/*
Provisioning Service

The Provisioning service provides REST APIs that are responsible for the provisioning and deprovisioning of environment instances and tenants in the corresponding region.  Provisioning is performed after validation by the Entitlements service. Use the APIs in this service to manage and create environment instances, such as a Cloud Foundry org, in a subaccount and to retrieve the plans and quota assignments for a subaccount.  See also: * [Authorization](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/3670474a58c24ac2b082e76cbbd9dc19.html) * [Rate Limiting](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77b217b3f57a45b987eb7fbc3305ce1e.html) * [Error Response Format](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77fef2fb104b4b1795e2e6cee790e8b8.html) * [Asynchronous Jobs](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/0a0a6ab0ad114d72a6611c1c6b21683e.html)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AvailableEnvironmentResponseCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AvailableEnvironmentResponseCollection{}

// AvailableEnvironmentResponseCollection struct for AvailableEnvironmentResponseCollection
type AvailableEnvironmentResponseCollection struct {
	AvailableEnvironments []AvailableEnvironmentResponseObject `json:"availableEnvironments,omitempty"`
}

// NewAvailableEnvironmentResponseCollection instantiates a new AvailableEnvironmentResponseCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAvailableEnvironmentResponseCollection() *AvailableEnvironmentResponseCollection {
	this := AvailableEnvironmentResponseCollection{}
	return &this
}

// NewAvailableEnvironmentResponseCollectionWithDefaults instantiates a new AvailableEnvironmentResponseCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAvailableEnvironmentResponseCollectionWithDefaults() *AvailableEnvironmentResponseCollection {
	this := AvailableEnvironmentResponseCollection{}
	return &this
}

// GetAvailableEnvironments returns the AvailableEnvironments field value if set, zero value otherwise.
func (o *AvailableEnvironmentResponseCollection) GetAvailableEnvironments() []AvailableEnvironmentResponseObject {
	if o == nil || IsNil(o.AvailableEnvironments) {
		var ret []AvailableEnvironmentResponseObject
		return ret
	}
	return o.AvailableEnvironments
}

// GetAvailableEnvironmentsOk returns a tuple with the AvailableEnvironments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AvailableEnvironmentResponseCollection) GetAvailableEnvironmentsOk() ([]AvailableEnvironmentResponseObject, bool) {
	if o == nil || IsNil(o.AvailableEnvironments) {
		return nil, false
	}
	return o.AvailableEnvironments, true
}

// HasAvailableEnvironments returns a boolean if a field has been set.
func (o *AvailableEnvironmentResponseCollection) HasAvailableEnvironments() bool {
	if o != nil && !IsNil(o.AvailableEnvironments) {
		return true
	}

	return false
}

// SetAvailableEnvironments gets a reference to the given []AvailableEnvironmentResponseObject and assigns it to the AvailableEnvironments field.
func (o *AvailableEnvironmentResponseCollection) SetAvailableEnvironments(v []AvailableEnvironmentResponseObject) {
	o.AvailableEnvironments = v
}

func (o AvailableEnvironmentResponseCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AvailableEnvironmentResponseCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvailableEnvironments) {
		toSerialize["availableEnvironments"] = o.AvailableEnvironments
	}
	return toSerialize, nil
}

type NullableAvailableEnvironmentResponseCollection struct {
	value *AvailableEnvironmentResponseCollection
	isSet bool
}

func (v NullableAvailableEnvironmentResponseCollection) Get() *AvailableEnvironmentResponseCollection {
	return v.value
}

func (v *NullableAvailableEnvironmentResponseCollection) Set(val *AvailableEnvironmentResponseCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableAvailableEnvironmentResponseCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableAvailableEnvironmentResponseCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAvailableEnvironmentResponseCollection(val *AvailableEnvironmentResponseCollection) *NullableAvailableEnvironmentResponseCollection {
	return &NullableAvailableEnvironmentResponseCollection{value: val, isSet: true}
}

func (v NullableAvailableEnvironmentResponseCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAvailableEnvironmentResponseCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


