/*
Provisioning Service

The Provisioning service provides REST APIs that are responsible for the provisioning and deprovisioning of environment instances and tenants in the corresponding region.  Provisioning is performed after validation by the Entitlements service. Use the APIs in this service to manage and create environment instances, such as a Cloud Foundry org, in a subaccount and to retrieve the plans and quota assignments for a subaccount.  See also: * [Authorization](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/3670474a58c24ac2b082e76cbbd9dc19.html) * [Rate Limiting](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77b217b3f57a45b987eb7fbc3305ce1e.html) * [Error Response Format](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77fef2fb104b4b1795e2e6cee790e8b8.html) * [Asynchronous Jobs](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/0a0a6ab0ad114d72a6611c1c6b21683e.html)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the QuotaResourcesResponseObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuotaResourcesResponseObject{}

// QuotaResourcesResponseObject struct for QuotaResourcesResponseObject
type QuotaResourcesResponseObject struct {
	// any relevant information about the resource that is not provided by other parameter values.
	AdditionalInfo map[string]map[string]interface{} `json:"additionalInfo,omitempty"`
	// Description of the resource.
	Description *string `json:"description,omitempty"`
	// Descriptive name of the resource for customer-facing UIs.
	DisplayName *string `json:"displayName,omitempty"`
	// Data associated with the resource.
	ResourceData map[string]map[string]interface{} `json:"resourceData,omitempty"`
	// Provider of the requested resource. For example, IaaS provider: AWS.
	ResourceProvider *string `json:"resourceProvider,omitempty"`
	// Unique technical name of the resource.
	ResourceTechnicalName *string `json:"resourceTechnicalName,omitempty"`
	// Type of the resource.
	ResourceType *string `json:"resourceType,omitempty"`
}

// NewQuotaResourcesResponseObject instantiates a new QuotaResourcesResponseObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuotaResourcesResponseObject() *QuotaResourcesResponseObject {
	this := QuotaResourcesResponseObject{}
	return &this
}

// NewQuotaResourcesResponseObjectWithDefaults instantiates a new QuotaResourcesResponseObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuotaResourcesResponseObjectWithDefaults() *QuotaResourcesResponseObject {
	this := QuotaResourcesResponseObject{}
	return &this
}

// GetAdditionalInfo returns the AdditionalInfo field value if set, zero value otherwise.
func (o *QuotaResourcesResponseObject) GetAdditionalInfo() map[string]map[string]interface{} {
	if o == nil || IsNil(o.AdditionalInfo) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.AdditionalInfo
}

// GetAdditionalInfoOk returns a tuple with the AdditionalInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaResourcesResponseObject) GetAdditionalInfoOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.AdditionalInfo) {
		return map[string]map[string]interface{}{}, false
	}
	return o.AdditionalInfo, true
}

// HasAdditionalInfo returns a boolean if a field has been set.
func (o *QuotaResourcesResponseObject) HasAdditionalInfo() bool {
	if o != nil && !IsNil(o.AdditionalInfo) {
		return true
	}

	return false
}

// SetAdditionalInfo gets a reference to the given map[string]map[string]interface{} and assigns it to the AdditionalInfo field.
func (o *QuotaResourcesResponseObject) SetAdditionalInfo(v map[string]map[string]interface{}) {
	o.AdditionalInfo = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *QuotaResourcesResponseObject) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaResourcesResponseObject) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *QuotaResourcesResponseObject) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *QuotaResourcesResponseObject) SetDescription(v string) {
	o.Description = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *QuotaResourcesResponseObject) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaResourcesResponseObject) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *QuotaResourcesResponseObject) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *QuotaResourcesResponseObject) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetResourceData returns the ResourceData field value if set, zero value otherwise.
func (o *QuotaResourcesResponseObject) GetResourceData() map[string]map[string]interface{} {
	if o == nil || IsNil(o.ResourceData) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.ResourceData
}

// GetResourceDataOk returns a tuple with the ResourceData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaResourcesResponseObject) GetResourceDataOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.ResourceData) {
		return map[string]map[string]interface{}{}, false
	}
	return o.ResourceData, true
}

// HasResourceData returns a boolean if a field has been set.
func (o *QuotaResourcesResponseObject) HasResourceData() bool {
	if o != nil && !IsNil(o.ResourceData) {
		return true
	}

	return false
}

// SetResourceData gets a reference to the given map[string]map[string]interface{} and assigns it to the ResourceData field.
func (o *QuotaResourcesResponseObject) SetResourceData(v map[string]map[string]interface{}) {
	o.ResourceData = v
}

// GetResourceProvider returns the ResourceProvider field value if set, zero value otherwise.
func (o *QuotaResourcesResponseObject) GetResourceProvider() string {
	if o == nil || IsNil(o.ResourceProvider) {
		var ret string
		return ret
	}
	return *o.ResourceProvider
}

// GetResourceProviderOk returns a tuple with the ResourceProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaResourcesResponseObject) GetResourceProviderOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceProvider) {
		return nil, false
	}
	return o.ResourceProvider, true
}

// HasResourceProvider returns a boolean if a field has been set.
func (o *QuotaResourcesResponseObject) HasResourceProvider() bool {
	if o != nil && !IsNil(o.ResourceProvider) {
		return true
	}

	return false
}

// SetResourceProvider gets a reference to the given string and assigns it to the ResourceProvider field.
func (o *QuotaResourcesResponseObject) SetResourceProvider(v string) {
	o.ResourceProvider = &v
}

// GetResourceTechnicalName returns the ResourceTechnicalName field value if set, zero value otherwise.
func (o *QuotaResourcesResponseObject) GetResourceTechnicalName() string {
	if o == nil || IsNil(o.ResourceTechnicalName) {
		var ret string
		return ret
	}
	return *o.ResourceTechnicalName
}

// GetResourceTechnicalNameOk returns a tuple with the ResourceTechnicalName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaResourcesResponseObject) GetResourceTechnicalNameOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceTechnicalName) {
		return nil, false
	}
	return o.ResourceTechnicalName, true
}

// HasResourceTechnicalName returns a boolean if a field has been set.
func (o *QuotaResourcesResponseObject) HasResourceTechnicalName() bool {
	if o != nil && !IsNil(o.ResourceTechnicalName) {
		return true
	}

	return false
}

// SetResourceTechnicalName gets a reference to the given string and assigns it to the ResourceTechnicalName field.
func (o *QuotaResourcesResponseObject) SetResourceTechnicalName(v string) {
	o.ResourceTechnicalName = &v
}

// GetResourceType returns the ResourceType field value if set, zero value otherwise.
func (o *QuotaResourcesResponseObject) GetResourceType() string {
	if o == nil || IsNil(o.ResourceType) {
		var ret string
		return ret
	}
	return *o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaResourcesResponseObject) GetResourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceType) {
		return nil, false
	}
	return o.ResourceType, true
}

// HasResourceType returns a boolean if a field has been set.
func (o *QuotaResourcesResponseObject) HasResourceType() bool {
	if o != nil && !IsNil(o.ResourceType) {
		return true
	}

	return false
}

// SetResourceType gets a reference to the given string and assigns it to the ResourceType field.
func (o *QuotaResourcesResponseObject) SetResourceType(v string) {
	o.ResourceType = &v
}

func (o QuotaResourcesResponseObject) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuotaResourcesResponseObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdditionalInfo) {
		toSerialize["additionalInfo"] = o.AdditionalInfo
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.ResourceData) {
		toSerialize["resourceData"] = o.ResourceData
	}
	if !IsNil(o.ResourceProvider) {
		toSerialize["resourceProvider"] = o.ResourceProvider
	}
	if !IsNil(o.ResourceTechnicalName) {
		toSerialize["resourceTechnicalName"] = o.ResourceTechnicalName
	}
	if !IsNil(o.ResourceType) {
		toSerialize["resourceType"] = o.ResourceType
	}
	return toSerialize, nil
}

type NullableQuotaResourcesResponseObject struct {
	value *QuotaResourcesResponseObject
	isSet bool
}

func (v NullableQuotaResourcesResponseObject) Get() *QuotaResourcesResponseObject {
	return v.value
}

func (v *NullableQuotaResourcesResponseObject) Set(val *QuotaResourcesResponseObject) {
	v.value = val
	v.isSet = true
}

func (v NullableQuotaResourcesResponseObject) IsSet() bool {
	return v.isSet
}

func (v *NullableQuotaResourcesResponseObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuotaResourcesResponseObject(val *QuotaResourcesResponseObject) *NullableQuotaResourcesResponseObject {
	return &NullableQuotaResourcesResponseObject{value: val, isSet: true}
}

func (v NullableQuotaResourcesResponseObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuotaResourcesResponseObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
