/*
Provisioning Service

The Provisioning service provides REST APIs that are responsible for the provisioning and deprovisioning of environment instances and tenants in the corresponding region.  Provisioning is performed after validation by the Entitlements service. Use the APIs in this service to manage and create environment instances, such as a Cloud Foundry org, in a subaccount and to retrieve the plans and quota assignments for a subaccount.  See also: * [Authorization](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/3670474a58c24ac2b082e76cbbd9dc19.html) * [Rate Limiting](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77b217b3f57a45b987eb7fbc3305ce1e.html) * [Error Response Format](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77fef2fb104b4b1795e2e6cee790e8b8.html) * [Asynchronous Jobs](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/0a0a6ab0ad114d72a6611c1c6b21683e.html)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateEnvironmentInstanceBindingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEnvironmentInstanceBindingRequest{}

// CreateEnvironmentInstanceBindingRequest JSON object with configuration parameters specific to environment instance binding as specified in the OSB API.
type CreateEnvironmentInstanceBindingRequest struct {
	Parameters map[string]interface{} `json:"parameters,omitempty"`
}

// NewCreateEnvironmentInstanceBindingRequest instantiates a new CreateEnvironmentInstanceBindingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEnvironmentInstanceBindingRequest() *CreateEnvironmentInstanceBindingRequest {
	this := CreateEnvironmentInstanceBindingRequest{}
	return &this
}

// NewCreateEnvironmentInstanceBindingRequestWithDefaults instantiates a new CreateEnvironmentInstanceBindingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEnvironmentInstanceBindingRequestWithDefaults() *CreateEnvironmentInstanceBindingRequest {
	this := CreateEnvironmentInstanceBindingRequest{}
	return &this
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *CreateEnvironmentInstanceBindingRequest) GetParameters() map[string]interface{} {
	if o == nil || IsNil(o.Parameters) {
		var ret map[string]interface{}
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentInstanceBindingRequest) GetParametersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Parameters) {
		return map[string]interface{}{}, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *CreateEnvironmentInstanceBindingRequest) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]interface{} and assigns it to the Parameters field.
func (o *CreateEnvironmentInstanceBindingRequest) SetParameters(v map[string]interface{}) {
	o.Parameters = v
}

func (o CreateEnvironmentInstanceBindingRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEnvironmentInstanceBindingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	return toSerialize, nil
}

type NullableCreateEnvironmentInstanceBindingRequest struct {
	value *CreateEnvironmentInstanceBindingRequest
	isSet bool
}

func (v NullableCreateEnvironmentInstanceBindingRequest) Get() *CreateEnvironmentInstanceBindingRequest {
	return v.value
}

func (v *NullableCreateEnvironmentInstanceBindingRequest) Set(val *CreateEnvironmentInstanceBindingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEnvironmentInstanceBindingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEnvironmentInstanceBindingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEnvironmentInstanceBindingRequest(val *CreateEnvironmentInstanceBindingRequest) *NullableCreateEnvironmentInstanceBindingRequest {
	return &NullableCreateEnvironmentInstanceBindingRequest{value: val, isSet: true}
}

func (v NullableCreateEnvironmentInstanceBindingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEnvironmentInstanceBindingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


