/*
Accounts Service

The Accounts service provides REST APIs that are responsible for the management of global accounts, and the creation and management of directories, subaccounts, and their custom properties/tags.  Global accounts represent a business entity and contain contract information, including customer details and purchased entitlements. The global account is the context for billing each customer.  Use the subaccount APIs to structure your global account according to your organization's and project's requirements regarding members, authorizations, and quotas. This service also provides you with APIs for creating and managing directories. While the use of directories is optional, they allow you to further organize and manage your subaccounts according to your specific technical and business needs. The service also lets you manage the custom properties/tags that you associate with your directories and subaccounts. NOTE: These APIs are relevant only for cloud management tools feature set B. For details and information about whether this applies to your global account, see [Cloud Management Tools - Feature Set Overview](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/caf4e4e23aef4666ad8f125af393dfb2.html).  See also: * [Authorization](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/3670474a58c24ac2b082e76cbbd9dc19.html) * [Rate Limiting](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77b217b3f57a45b987eb7fbc3305ce1e.html) * [Error Response Format](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77fef2fb104b4b1795e2e6cee790e8b8.html) * [Asynchronous Jobs](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/0a0a6ab0ad114d72a6611c1c6b21683e.html)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResponseCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseCollection{}

// ResponseCollection struct for ResponseCollection
type ResponseCollection struct {
	Value []SubaccountResponseObject `json:"value,omitempty"`
}

// NewResponseCollection instantiates a new ResponseCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseCollection() *ResponseCollection {
	this := ResponseCollection{}
	return &this
}

// NewResponseCollectionWithDefaults instantiates a new ResponseCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseCollectionWithDefaults() *ResponseCollection {
	this := ResponseCollection{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ResponseCollection) GetValue() []SubaccountResponseObject {
	if o == nil || IsNil(o.Value) {
		var ret []SubaccountResponseObject
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCollection) GetValueOk() ([]SubaccountResponseObject, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ResponseCollection) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given []SubaccountResponseObject and assigns it to the Value field.
func (o *ResponseCollection) SetValue(v []SubaccountResponseObject) {
	o.Value = v
}

func (o ResponseCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableResponseCollection struct {
	value *ResponseCollection
	isSet bool
}

func (v NullableResponseCollection) Get() *ResponseCollection {
	return v.value
}

func (v *NullableResponseCollection) Set(val *ResponseCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseCollection(val *ResponseCollection) *NullableResponseCollection {
	return &NullableResponseCollection{value: val, isSet: true}
}

func (v NullableResponseCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


