{
  "openapi": "3.0.1",
  "info": {
    "title": "SAP XSUAA REST API",
    "description": "Provides access to RoleTemplates, Roles, RoleCollection etc. using the XSUAA REST API",
    "termsOfService": "",
    "contact": {},
    "license": {
      "name": "SAP SE, Walldorf, Germany",
      "url": "https://support.sap.com/en/my-support/keys.html"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://xsuaa-provisioning.cf.sap.hana.ondemand.com",
      "description": "Generated server url"
    }
  ],
  "tags": [
    {
      "name": "application",
      "description": "API for providing access to XSUAA applications"
    },
    {
      "name": "idp-role-collection",
      "description": "API for providing access to XSUAA IDP groups to role collections mappings"
    },
    {
      "name": "identity-providers",
      "description": "API for providing access to XSUAA identity providers"
    },
    {
      "name": "roles",
      "description": "API for providing access to the XSUAA roles"
    },
    {
      "name": "usercontroller",
      "description": "API for managing user entries and role collections assignments"
    },
    {
      "name": "roletemplates",
      "description": "API for providing access to the XSUAA role templates"
    },
    {
      "name": "customidp",
      "description": "API to check if more custom platform IdP trusts are allowed"
    },
    {
      "name": "rolecollections",
      "description": "API for providing access to the xsuaa role collections"
    },
    {
      "name": "tenant",
      "description": "The tenants API"
    },
    {
      "name": "customidp",
      "description": "API to set the neoAuthN flag or check if set"
    }
  ],
  "paths": {
    "/sap/rest/user": {
      "put": {
        "tags": [
          "usercontroller"
        ],
        "summary": "Update a user",
        "description": "Updates an existing user",
        "operationId": "updateUser"
      },
      "post": {
        "tags": [
          "usercontroller"
        ],
        "summary": "Create user",
        "description": "Creates a new user from the payload",
        "operationId": "createUser"
      }
    },
    "/sap/rest/user/origin/{origin}/name/{userName}/rolecollections/{roleCollectionName}": {
      "put": {
        "tags": [
          "usercontroller"
        ],
        "summary": "Add role collection to user",
        "description": "Assigns a role collection to a user. The user can be created if they do not exist yet.",
        "operationId": "addRoleCollection"
      },
      "delete": {
        "tags": [
          "usercontroller"
        ],
        "summary": "Remove role collection from user",
        "description": "Unassigns a role collection from a user.",
        "operationId": "removeRoleCollection"
      }
    },
    "/sap/rest/platform-identity-providers-global/{originKey}": {
      "get": {
        "tags": [
          "platform-identity-providers-global"
        ],
        "summary": "Reads a custom platform identity provider.",
        "description": "Reads a custom platform IdP from own region.",
        "operationId": "getPlatformIdentityProvider",
        "security": [
          {
            "xs_idp_global": [
              "xs_idp_global.write"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "platform-identity-providers-global"
        ],
        "summary": "Updates a custom platform identity provider.",
        "description": "Updates a custom platform IdP and distributes the information in the own region.",
        "operationId": "updatePlatformIdentityProvider",
        "security": [
          {
            "xs_idp_global": [
              "xs_idp_global.write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "platform-identity-providers-global"
        ],
        "summary": "Deletes a custom platform identity provider.",
        "description": "Deletes a custom platform IdP and distributes the information in the own region.",
        "operationId": "deletePlatformIdentityProvider",
        "security": [
          {
            "xs_idp_global": [
              "xs_idp_global.write"
            ]
          }
        ]
      }
    },
    "/sap/rest/identity-providers/{id}": {
      "get": {
        "tags": [
          "identity-providers"
        ],
        "summary": "Returns an identity provider.",
        "description": "Returns an identity provider specified by the id of the identity provider.",
        "operationId": "retrieveIdentityProvider",
        "security": [
          {
            "xs_auth": [
              "xs_idp.read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "identity-providers"
        ],
        "operationId": "updateIdentityProvider"
      },
      "delete": {
        "tags": [
          "identity-providers"
        ],
        "operationId": "deleteIdentityProvider"
      }
    },
    "/sap/rest/identity-providers/migrate/{origin}": {
      "put": {
        "tags": [
          "identity-providers"
        ],
        "operationId": "migrateSAMLToOIDCIDP"
      }
    },
    "/sap/rest/identity-providers/migrate/{origin}/rollback": {
      "put": {
        "tags": [
          "identity-providers"
        ],
        "operationId": "rollbackSAMLToOIDCIDP"
      }
    },
    "/sap/rest/authorization/v2/rolecollections/{roleCollectionName}": {
      "get": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Returns a role collection.",
        "description": "Returns information about a role collection identified by the name of the role collection.",
        "operationId": "getRoleCollectionByName",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Updates the description of a role collection.",
        "description": "Updates the description of a role collection specified by the name of the role collection. You cannot change any other attribute of the role collection.",
        "operationId": "changeRoleCollectionDescription",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read",
              "xs_authorization.write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Deletes a role collection.",
        "description": "Deletes a role collection specified by the name of the role collection.",
        "operationId": "deleteRoleCollectionByName",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.write"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/rolecollections/{roleCollectionName}/roles": {
      "get": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Returns the roles of a role collection.",
        "description": "Returns information about the roles of a role collection specified by the name of the role collection.",
        "operationId": "getRolesByRoleCollectionName",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Add roles to role collection.",
        "description": "Updates a role collection with an array of roles. Specify the roles by role name, application ID, and role template name. These roles are added to the roles already included in the role collection.",
        "operationId": "addRolesToRoleCollection",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.write",
              "xs_authorization.write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Remove roles from role collection.",
        "description": "Updates a role collection by removing an array of roles from role collection. Specify the roles by role name, application ID, and role template name. These roles are removed from the role collection.",
        "operationId": "deleteRolesFromRoleCollection",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read",
              "xs_authorization.write"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/rolecollections/{roleCollectionName}/roles/{roleTemplateAppID}/{roleName}/{roleTemplateName}": {
      "put": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Adds a role to role a collection.",
        "description": "Adds a role reference, specified by role name, application ID, and role template name, to a role collection.",
        "operationId": "addRoleToRoleCollection",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read",
              "xs_authorization.write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Deletes a role from a role collection.",
        "description": "Deletes a role specified by the role reference from a role collection.",
        "operationId": "deleteRoleFromRoleCollection",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read",
              "xs_authorization.write"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/apps/{appId}/roletemplates/{templateName}/roles/{roleName}": {
      "get": {
        "tags": [
          "roles"
        ],
        "summary": "Returns the role of a service instance.",
        "description": "Returns a role specified by the app ID, role template, and role name.",
        "operationId": "getRoleByAppAndRoleTemplate",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "roles"
        ],
        "summary": "Updates a role",
        "description": "Updates a role specfied by app ID, role template name, and role name.",
        "operationId": "updateRole",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read",
              "xs_authorization.write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "roles"
        ],
        "summary": "Deletes a role.",
        "description": "Deletes a role specfied by app ID, role template name, and role name.",
        "operationId": "deleteRoleByRoleName",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read",
              "xs_authorization.write"
            ]
          }
        ]
      }
    },
    "/sap/rest/user/bulk": {
      "post": {
        "tags": [
          "usercontroller"
        ],
        "summary": "Create multiple users",
        "description": "Creates a set of users from the list in the payload",
        "operationId": "createUsers"
      }
    },
    "/sap/rest/platform-identity-providers-global": {
      "get": {
        "tags": [
          "platform-identity-providers-global"
        ],
        "summary": "Reads all custom platform identity providers.",
        "description": "Reads all custom platform IdPs from own region.",
        "operationId": "getPlatformIdentityProviders",
        "security": [
          {
            "xs_idp_global": [
              "xs_idp_global.write"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "platform-identity-providers-global"
        ],
        "summary": "Creates a custom platform identity provider.",
        "description": "Creates a custom platform IdP and distributes the information in the own region.",
        "operationId": "createPlatformIdentityProvider",
        "security": [
          {
            "xs_idp_global": [
              "xs_idp_global.write"
            ]
          }
        ]
      }
    },
    "/sap/rest/platform-identity-providers-global/{originKey}/globalaccountids": {
      "get": {
        "tags": [
          "platform-identity-providers-global"
        ],
        "summary": "Reads GlobalAccountIds.",
        "description": "Reads GlobalAccountIds of a custom platform IdP.",
        "operationId": "getPlatformIdentityProviderGlobalAccountIds",
        "security": [
          {
            "xs_idp_global": [
              "xs_idp_global.read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "platform-identity-providers-global"
        ],
        "summary": "Adds a globalAccountId.",
        "description": "Adds a globalAccountId to a custom platform IdP.",
        "operationId": "addPlatformIdentityProviderGlobalAccountId",
        "security": [
          {
            "xs_idp_global": [
              "xs_idp_global.write"
            ]
          }
        ]
      }
    },
    "/sap/rest/platform-identity-providers-global/refreshTrusts": {
      "post": {
        "tags": [
          "platform-identity-providers-global"
        ],
        "summary": "Refreshes platform Identity Provider trusts.",
        "description": "Refreshes all platform Identity Provider trusts or trusts provided in the body.",
        "operationId": "refreshPlatformIdentityProviderTrusts",
        "security": [
          {
            "xs_idp_global": [
              "xs_idp_global.write"
            ]
          }
        ]
      }
    },
    "/sap/rest/identity-providers": {
      "get": {
        "tags": [
          "identity-providers"
        ],
        "summary": "Returns a list of identity providers.",
        "description": "Returns a list of identity providers for the current subaccount.",
        "operationId": "retrieveIdentityProviders",
        "security": [
          {
            "xs_auth": [
              "xs_idp.read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "identity-providers"
        ],
        "summary": "Creates an identity provider.",
        "description": "Creates an identity provider based on a configuration in JSON format.",
        "operationId": "createIdentityProvider",
        "security": [
          {
            "xs_auth": [
              "xs_idp.write"
            ]
          }
        ]
      }
    },
    "/sap/rest/globalaccount/{globalAccountId}/platform-identity-providers": {
      "get": {
        "tags": [
          "platform-identity-providers"
        ],
        "summary": "Reads all platform IdPs for token GA.",
        "description": "Reads all platform identity providers as help values for token GA.",
        "operationId": "getPlatformIdentityProvidersForGA",
        "security": [
          {
            "xs_idp": [
              "xs_idp.read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "platform-identity-providers"
        ],
        "summary": "Adds GA Trust for a given origin.",
        "description": "Adds a Trust for a platform identity provider.",
        "operationId": "addPlatformIdentityProviderTrust",
        "security": [
          {
            "xs_idp": [
              "xs_idp.write"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/users/current/rolecollections": {
      "get": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Get role collections of User",
        "description": "all role collections for a user",
        "operationId": "getRoleCollectionsForUser_1"
      },
      "post": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Create bulk role collections for a User",
        "description": "create role collections for a user",
        "operationId": "createRoleCollectionsForUser",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Delete bulk role collections of User",
        "description": "delete role collections for a user",
        "operationId": "deleteRoleCollectionsForUser",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.write"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/rolecollections": {
      "get": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Returns role collections.",
        "description": "Returns all role collections which exist within the current subaccount, sorted alphabetically by their names.",
        "operationId": "getRoleCollections",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Creates a role collection.",
        "description": "Creates a role collection. You must include a role name at a minimum. The description is created as null if you do not include one. You can include role references as defined by the role name, the application ID, and role template name. To assign group members use the /Groups endpoint. Groups are mapped to role collections in the Authorization and Trust Management service.",
        "operationId": "createRoleCollection",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read",
              "xs_authorization.write"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/rolecollections/bulk": {
      "post": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Bulk creation of role collections.",
        "description": "Bulk create of role collections specified by the name of the role collection.",
        "operationId": "createRoleCollections",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Bulk delete of role collections.",
        "description": "Bulk delete of role collections specified by the name of the role collection.",
        "operationId": "deleteRoleCollections",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.write"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/identity-providers/{origin}/attributes": {
      "post": {
        "tags": [
          "idp-role-collection"
        ],
        "summary": "Add a Idp attribute with value and operator to a role collection",
        "description": "Add an attribute with value and operation to current IdP and application role collection.",
        "operationId": "addIdpAttributeToRoleCollection",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/apps/roles": {
      "post": {
        "tags": [
          "roles"
        ],
        "summary": "Creates a role for an application.",
        "description": "Create a role for an application based on a role template. You must define the role name and description as well as identify the application and the role template name that you want to include in the role. The role inherits the scopes of the role template.",
        "operationId": "createRole",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read",
              "xs_authorization.write"
            ]
          }
        ]
      }
    },
    "/Users": {
      "get": {
        "tags": [
          "scim-user-endpoints"
        ],
        "operationId": "findUsers"
      },
      "post": {
        "tags": [
          "scim-user-endpoints"
        ],
        "operationId": "createUser_1"
      }
    },
    "/Groups": {
      "get": {
        "tags": [
          "scim-group-endpoints"
        ],
        "operationId": "listGroups"
      },
      "post": {
        "tags": [
          "scim-group-endpoints"
        ],
        "operationId": "createGroup"
      }
    },
    "/sap/rest/globalaccount/{globalAccountId}/platform-identity-providers/{originKey}": {
      "delete": {
        "tags": [
          "platform-identity-providers"
        ],
        "summary": "Deletes a GA Trust for given origin.",
        "description": "Deletes a trust for a platform identity provider.",
        "operationId": "deletePlatformIdentityProviderTrust",
        "security": [
          {
            "xs_idp": [
              "xs_idp.write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "platform-identity-providers"
        ],
        "summary": "Updates a GA Trust for given origin.",
        "description": "Updates a trust for a platform identity provider.",
        "operationId": "updatePlatformIdentityProviderTrust",
        "security": [
          {
            "xs_idp": [
              "xs_idp.write"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/securitySettings": {
      "get": {
        "tags": [
          "tenant"
        ],
        "summary": "Reads settings of a tenant",
        "operationId": "readSettings",
        "security": [
          {
            "tenant_auth": [
              "xs_tenant.read",
              "xs_authorization.read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "tenant"
        ],
        "description": "Updates settings of a tenant",
        "operationId": "updateSettings",
        "security": [
          {
            "tenant_auth": [
              "xs_authorization.write",
              "xs_tenant.write"
            ]
          }
        ]
      }
    },
    "/sap/rest/user/origin": {
      "get": {
        "tags": [
          "usercontroller"
        ],
        "summary": "Get origins of users",
        "description": "Returns all unique origin values of all users in the account.",
        "operationId": "getOrigins"
      }
    },
    "/sap/rest/user/origin/{origin}/name": {
      "get": {
        "tags": [
          "usercontroller"
        ],
        "summary": "Get usernames",
        "description": "Returns all usernames in the account, sorted alphabetically",
        "operationId": "getUserNames"
      }
    },
    "/sap/rest/user/origin/{origin}/name/{username}": {
      "get": {
        "tags": [
          "usercontroller"
        ],
        "summary": "Get a specifiy user",
        "description": "Returns the user record of the specified username and origin",
        "operationId": "getUserByName"
      }
    },
    "/sap/rest/user/id/{id}": {
      "get": {
        "tags": [
          "usercontroller"
        ],
        "summary": "Read user by ID",
        "description": "Retrieves a user with the specified ID",
        "operationId": "getUserById"
      },
      "delete": {
        "tags": [
          "usercontroller"
        ],
        "summary": "Delete a user",
        "description": "Deletes an existing user with the specified user ID",
        "operationId": "deleteUserById"
      }
    },
    "/sap/rest/tenantLoginInfo/{subdomain}": {
      "get": {
        "tags": [
          "zone-trust-information"
        ],
        "summary": "Get Zone information for tenant",
        "operationId": "getZoneInformationBySubdomain"
      }
    },
    "/sap/rest/neo/platformidentityproviders": {
      "get": {
        "tags": [
          "customidp"
        ],
        "summary": "Returns the feature flag value for a neo user for a IAS tenant",
        "description": "Returns the feature flag value for a neo user for a IAS tenant",
        "operationId": "getCustomIdPFeatureFlagForNeoUser"
      }
    },
    "/sap/rest/identity-providers/ias": {
      "get": {
        "tags": [
          "identity-providers"
        ],
        "summary": "Returns a list of valid IAS tenants.",
        "description": "For the current XSUAA tenant, returns those IAS tenants for which no SAML trust has been set up yet.",
        "operationId": "retrieveIasTenants",
        "security": [
          {
            "xs_auth": [
              "xs_idp.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/identity-providers/ias/{tenantURL}": {
      "get": {
        "tags": [
          "identity-providers"
        ],
        "summary": "Returns a specific IAS tenant.",
        "description": "Returns a specific IAS tenants for the current XSUAA tenant.",
        "operationId": "retrieveSpecificIasTenant",
        "security": [
          {
            "xs_auth": [
              "xs_idp.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/identity-providers/ias/status": {
      "get": {
        "tags": [
          "identity-providers"
        ],
        "summary": "Returns the status of IAS registry.",
        "description": "Returns the current status of the IAS registry component. This includes a json payload containing errors or a health statement.",
        "operationId": "getRegistryStatus"
      }
    },
    "/sap/rest/identity-providers/btpcli/identity-providers": {
      "get": {
        "tags": [
          "identity-providers"
        ],
        "operationId": "retrieveIdentityProvidersForBtpCliDeprecated",
        "deprecated": true
      }
    },
    "/sap/rest/globalaccount/{globalAccountId}/platform-identity-providers/status": {
      "get": {
        "tags": [
          "customidp"
        ],
        "summary": "Return whether multiple custom platform IdP trusts are allowed",
        "description": "Return whether multiple custom platform IdP trusts are allowed",
        "operationId": "areMoreTrustsAllowed",
        "security": [
          {
            "xs_idp": [
              "xs_idp.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/zoneinfo/{subdomain}": {
      "get": {
        "tags": [
          "zone-trust-information"
        ],
        "summary": "Get Zone information for tenant",
        "operationId": "getZoneInformationBySubdomain_1"
      }
    },
    "/sap/rest/authorization/v2/users/{userId}/rolecollections": {
      "get": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Get role collections of User",
        "description": "all role collections for a user",
        "operationId": "getRoleCollectionsForUser"
      }
    },
    "/sap/rest/authorization/v2/securitySettings/public": {
      "get": {
        "tags": [
          "tenant"
        ],
        "summary": "Reads public settings of a tenant",
        "operationId": "readPublicSettings"
      }
    },
    "/sap/rest/authorization/v2/roles": {
      "get": {
        "tags": [
          "roles"
        ],
        "summary": "Returns the roles of all service instances.",
        "description": "Returns all application roles for all service instances which are registered at UAA as OAuth2 client, sorted alphabetically by their name and roleTemplateAppId. The roles that are returned are limited to the subaccount credentials that are used for this request.",
        "operationId": "getRoles",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/rolecollections/roles/{appId}/{roleTemplateName}/{roleName}": {
      "get": {
        "tags": [
          "rolecollections",
          "application"
        ],
        "summary": "Get RoleCollections containing a role identified by appId, roleTemplateName and role name",
        "description": "Retrieve all RoleCollections containing a role. The role is identified by appId, roleTemplateName and role name.",
        "operationId": "getRoleCollectionsByAppIdTemplateNameAndRoleName",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read",
              "xs_authorization.write"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/rolecollections/pages/{pageId}": {
      "get": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Returns a page of role collections.",
        "description": "Returns the specified page of role collection search result. The role collections are the result of a previous paged GET request for role collections of the current subaccount.",
        "operationId": "getRoleCollectionsByPaging",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/rolecollections/pages": {
      "get": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Returns a page of role collections.",
        "description": "Returns the specified page of role collection search result. The role collections are the result of a previous paged GET request for role collections of the current subaccount.",
        "operationId": "getRoleCollectionsByPaging_1",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/rolecollections/pages/": {
      "get": {
        "tags": [
          "rolecollections"
        ],
        "summary": "Returns a page of role collections.",
        "description": "Returns the specified page of role collection search result. The role collections are the result of a previous paged GET request for role collections of the current subaccount.",
        "operationId": "getRoleCollectionsByPaging_2",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/ownapp": {
      "get": {
        "tags": [
          "application"
        ],
        "summary": "Returns information about the service instance used to execute this API access.",
        "description": "Returns information about the service instance which is associated with the client credentials you submitted with this REST call.",
        "operationId": "getOwnApp",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/ownapp/usage": {
      "get": {
        "tags": [
          "application"
        ],
        "summary": "Returns usage information for the service instance which is used to execute API access.",
        "description": "Returns the number of subscribers for the service instance which is associated with the client credentials you submitted with this REST call.",
        "operationId": "getAppByToken",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/identity-providers/{origin}/rolecollections/{roleCollectionName}": {
      "get": {
        "tags": [
          "idp-role-collection"
        ],
        "summary": "Get attributes and role collections from IdP",
        "description": "Read all attributes for current IdP and application role collection.",
        "operationId": "getIdpAttributeValuesFromRoleCollection",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/identity-providers/{origin}/attributes/{attributeName}/{attributeValue}": {
      "get": {
        "tags": [
          "idp-role-collection"
        ],
        "summary": "Read role collections from current attribute value and IdP",
        "description": "List of application role collections which are assigned to the current idP and the current attribute/value",
        "operationId": "getRoleCollectionByAttributeValue",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/identity-providers/{origin}/attributes/{attributeName}/rolecollections/{roleCollectionName}": {
      "get": {
        "tags": [
          "idp-role-collection"
        ],
        "summary": "Read all attributes for current IdP and application role collection",
        "description": "ist of Idp attribute value of a role collection for current attribute name",
        "operationId": "getIdpAttributeValuesFromRoleCollectionByAttribute",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/identity-providers/{origin}/attributes/rolecollections": {
      "get": {
        "tags": [
          "idp-role-collection"
        ],
        "summary": "Get attributes and role collection of IdP",
        "description": "Read all attributes for current IdP and application role collection.",
        "operationId": "getIdpAttributeValues",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/apps": {
      "get": {
        "tags": [
          "application"
        ],
        "summary": "Returns registered service instances of the current subaccount.",
        "description": "Returns all service instances of the current subaccount which are registered at the Authorization and Trust Management service as OAuth 2.0 clients. The system provides information about the XSUAA application and its OAuth client.",
        "operationId": "getApps",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/apps/{id}": {
      "get": {
        "tags": [
          "application"
        ],
        "summary": "Returns information about an XSUAA application instance.",
        "description": "Returns information about an XSUAA application instance specified by the app ID or service instance ID. The XSUAA application instance paired with an OAuth client defines a service instance of the Authorization and Trust Management service.",
        "operationId": "getAppById",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/apps/{appId}/scopes": {
      "get": {
        "tags": [
          "application"
        ],
        "summary": "Returns the scopes of an application.",
        "description": "Returns all scopes of an application protected by a service instance of the Authorization and Trust Management service.",
        "operationId": "listScopes",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/apps/{appId}/scopes/{scopeName}": {
      "get": {
        "tags": [
          "application"
        ],
        "summary": "Returns the scope of an application.",
        "description": "Returns information about a specific scope of a specific application.",
        "operationId": "getScope",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/apps/{appId}/roletemplates": {
      "get": {
        "tags": [
          "roletemplates"
        ],
        "summary": "Returns role templates for an application.",
        "description": "Returns information about all role templates for an application that is specified by the application ID.",
        "operationId": "getRoleTemplateByAppName",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/apps/{appId}/roletemplates/{templateName}": {
      "get": {
        "tags": [
          "roletemplates"
        ],
        "summary": "Returns a role template of an application.",
        "description": "Returns information about a role template of an application, which is specified by the application ID and the role template name.",
        "operationId": "getRoleTemplateByName",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/apps/{appId}/roles": {
      "get": {
        "tags": [
          "roles"
        ],
        "summary": "Returns the roles of an application",
        "description": "Returns all roles of an application specified by the application ID.",
        "operationId": "getRolesByAppId",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/apps/{appId}/authorizationData": {
      "get": {
        "tags": [
          "ams"
        ],
        "summary": "Get authorization data ",
        "description": "Retrieve authorization data for a given appId.",
        "operationId": "getAuthorizationData",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/apps/{appId}/authorities": {
      "get": {
        "tags": [
          "application"
        ],
        "summary": "Returns a list of authorities granted to an application.",
        "description": "Returns a list of authorities that have been granted to an application. <ul><li>The granting application is identified by the <var>grantedByAppGuid</var> or <var>grantedByAppId</var> parameter. If no granting application is specified the list will be empty.</li><li>The request has to be authenticated with a JWT obtained via the client credentials grant from the granted application. The JWT has to include the <var>uaa.resource</var> scope.</li></ul>",
        "operationId": "getGrantedAuthorities",
        "security": [
          {
            "uaa.resource": [
              "uaa.resource"
            ]
          }
        ]
      }
    },
    "/sap/rest/authorization/v2/apps/roletemplates": {
      "get": {
        "tags": [
          "roletemplates"
        ],
        "summary": "Returns all role templates.",
        "description": "Returns information about all role templates of applications protected by the service instance of the Authorization and Trust Management service. description: Returns all role templates",
        "operationId": "getRoleTemplates",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/user/origin/{origin}/name/{userName}": {
      "delete": {
        "tags": [
          "usercontroller"
        ],
        "summary": "Delete a user by username and origin",
        "description": "Deletes an existing user with the specified username and origin",
        "operationId": "deleteUserByName"
      }
    },
    "/sap/rest/platform-identity-providers-global/{originKey}/globalaccountids/{globalAccountId}": {
      "delete": {
        "tags": [
          "platform-identity-providers-global"
        ],
        "summary": "Deletes a globalAccountId.",
        "description": "Deletes a globalAccountId to a custom platform IdP.",
        "operationId": "deletePlatformIdentityProviderGlobalAccountId",
        "security": [
          {
            "xs_idp_global": [
              "xs_idp_global.write"
            ]
          }
        ]
      }
    },
    "/sap/rest/identity-providers/originKey/{originKey}": {
      "delete": {
        "tags": [
          "identity-providers"
        ],
        "operationId": "deleteIdentityProviderUsingOriginKey"
      }
    },
    "/sap/rest/authorization/v2/identity-providers/{origin}/attributes/{attributeName}/{operator}/{attributeValue}/rolecollections/{roleCollectionName}": {
      "delete": {
        "tags": [
          "idp-role-collection"
        ],
        "summary": "delete attribute with value from a role collection",
        "description": "Delete an attribute value for the current attribute within current IdP and application role collection",
        "operationId": "deleteIdpAttributeToRoleCollection",
        "security": [
          {
            "xs_auth": [
              "xs_authorization.read"
            ]
          }
        ]
      }
    },
    "/sap/rest/identity-providers/btpcli/originKey/{originKey}": {
      "get": {
        "tags": [
          "identity-providers"
        ],
        "operationId": "retrieveIdentityProviderByOriginKeyDeprecated_5",
        "deprecated": true
      },
      "put": {
        "tags": [
          "identity-providers"
        ],
        "operationId": "retrieveIdentityProviderByOriginKeyDeprecated_1",
        "deprecated": true
      },
      "post": {
        "tags": [
          "identity-providers"
        ],
        "operationId": "retrieveIdentityProviderByOriginKeyDeprecated_4",
        "deprecated": true
      },
      "delete": {
        "tags": [
          "identity-providers"
        ],
        "operationId": "retrieveIdentityProviderByOriginKeyDeprecated_3",
        "deprecated": true
      },
      "options": {
        "tags": [
          "identity-providers"
        ],
        "operationId": "retrieveIdentityProviderByOriginKeyDeprecated_2",
        "deprecated": true
      },
      "head": {
        "tags": [
          "identity-providers"
        ],
        "operationId": "retrieveIdentityProviderByOriginKeyDeprecated",
        "deprecated": true
      },
      "patch": {
        "tags": [
          "identity-providers"
        ],
        "operationId": "retrieveIdentityProviderByOriginKeyDeprecated_6",
        "deprecated": true
      }
    }
  },
  "components": {
    "securitySchemes": {
      "xs_auth": {
        "type": "oauth2",
        "description": "This API uses OAuth2 with the client-credentials flow.",
        "name": "xs_auth",
        "flows": {
          "clientCredentials": {
            "authorizationUrl": "/token",
            "scopes": {
              "xs_authorization.read": "for read operations",
              "xs_authorization.write": "for create and update operations"
            }
          }
        }
      },
      "xs_sub": {
        "type": "oauth2",
        "description": "This API uses OAuth2 with the client-credentials flow.",
        "name": "xs_sub",
        "flows": {
          "clientCredentials": {
            "authorizationUrl": "/token",
            "scopes": {
              "xs_subscription.read": "for read operations",
              "xs_subscription.write": "for create and update operations"
            }
          }
        }
      },
      "xs_tenant": {
        "type": "oauth2",
        "description": "This API uses OAuth2 with the client-credentials flow.",
        "name": "xs_tenant",
        "flows": {
          "clientCredentials": {
            "authorizationUrl": "/token",
            "scopes": {
              "xs_tenant.read": "for read operations",
              "xs_tenant.write": "for create and update operations"
            }
          }
        }
      },
      "xs_idp": {
        "type": "oauth2",
        "description": "This API uses OAuth2 with the client-credentials flow.",
        "name": "xs_idp",
        "flows": {
          "clientCredentials": {
            "authorizationUrl": "/token",
            "scopes": {
              "xs_idp.read": "for read operations",
              "xs_idp.write": "for modifying operations"
            }
          }
        }
      },
      "xs_idp_global": {
        "type": "oauth2",
        "description": "This API uses OAuth2 with the client-credentials flow.",
        "name": "xs_idp_global",
        "flows": {
          "clientCredentials": {
            "authorizationUrl": "/token",
            "scopes": {
              "xs_idp_global.read": "for read operations",
              "xs_idp_global.write": "for modifying operations"
            }
          }
        }
      },
      "uaa.resource": {
        "type": "oauth2",
        "description": "This API uses OAuth2 with the client-credentials flow.",
        "name": "uaa.resource",
        "flows": {
          "clientCredentials": {
            "authorizationUrl": "/token",
            "scopes": {
              "uaa.resource": "Identifies a JWT obtained via the client credentials grant."
            }
          }
        }
      }
    }
  }
}